---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quay.io
  resources:
  - groups
  - organizations
  - quayconfigs
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quay.io
  resources:
  - groups/finalizers
  - organizations/finalizers
  - quayconfigs/finalizers
  - teams/finalizers
  verbs:
  - update
- apiGroups:
  - quay.io
  resources:
  - groups/status
  - organizations/status
  - quayconfigs/status
  - teams/status
  verbs:
  - get
  - patch
  - update
